import { useState, useEffect } from 'react';

// Sarawak divisions with hospitals - Miri first for default focus
const DIVISIONS = {
  miri: {
    name: 'Miri Division',
    shortName: 'Miri',
    color: '#f59e0b', // MedChain Gold - featured
    hospitals: [
      { name: 'Miri General', fullName: 'Miri General Hospital', type: 'Government', beds: 460 },
      { name: 'Columbia Asia', fullName: 'Columbia Asia Miri', type: 'Private', beds: 100 },
      { name: 'KPJ Miri', fullName: 'KPJ Miri Specialist', type: 'Private', beds: 120 },
      { name: 'Marudi Hospital', fullName: 'Marudi Hospital', type: 'Government', beds: 60 },
      { name: 'Limbang Hospital', fullName: 'Limbang Hospital', type: 'Government', beds: 90 },
      { name: 'Lawas Hospital', fullName: 'Lawas Hospital', type: 'Government', beds: 50 },
    ],
    position: { x: 78, y: 22 },
  },
  kuching: {
    name: 'Kuching Division',
    shortName: 'Kuching',
    color: '#3b82f6', // MedChain Blue
    hospitals: [
      { name: 'Sarawak General', fullName: 'Sarawak General Hospital', type: 'Government', beds: 850 },
      { name: 'KPJ Kuching', fullName: 'KPJ Kuching Specialist', type: 'Private', beds: 200 },
      { name: 'Normah Medical', fullName: 'Normah Medical Specialist', type: 'Private', beds: 180 },
      { name: 'Timberland MC', fullName: 'Timberland Medical Centre', type: 'Private', beds: 150 },
      { name: 'Borneo Medical', fullName: 'Borneo Medical Centre', type: 'Private', beds: 120 },
      { name: 'Bau Hospital', fullName: 'Bau Hospital', type: 'Government', beds: 60 },
      { name: 'Lundu Hospital', fullName: 'Lundu Hospital', type: 'Government', beds: 45 },
      { name: 'Serian Hospital', fullName: 'Serian Hospital', type: 'Government', beds: 80 },
    ],
    position: { x: 18, y: 78 },
  },
  sibu: {
    name: 'Sibu Division',
    shortName: 'Sibu',
    color: '#8b5cf6', // Purple
    hospitals: [
      { name: 'Sibu Hospital', fullName: 'Sibu Hospital', type: 'Government', beds: 540 },
      { name: 'Rejang Medical', fullName: 'Rejang Medical Centre', type: 'Private', beds: 150 },
      { name: 'Selangau District', fullName: 'Selangau District Hospital', type: 'Government', beds: 40 },
      { name: 'Kapit Hospital', fullName: 'Kapit Hospital', type: 'Government', beds: 120 },
      { name: 'Sarikei Hospital', fullName: 'Sarikei Hospital', type: 'Government', beds: 180 },
    ],
    position: { x: 45, y: 55 },
  },
  bintulu: {
    name: 'Bintulu Division',
    shortName: 'Bintulu',
    color: '#10b981', // Emerald
    hospitals: [
      { name: 'Bintulu Hospital', fullName: 'Bintulu Hospital', type: 'Government', beds: 290 },
      { name: 'Mukah Hospital', fullName: 'Mukah Hospital', type: 'Government', beds: 120 },
      { name: 'Sri Aman Hospital', fullName: 'Sri Aman Hospital', type: 'Government', beds: 150 },
      { name: 'Betong Hospital', fullName: 'Betong Hospital', type: 'Government', beds: 80 },
      { name: 'Saratok Hospital', fullName: 'Saratok Hospital', type: 'Government', beds: 60 },
    ],
    position: { x: 60, y: 40 },
  },
};

// Fraud hotspot positions for red heatmap overlay
const FRAUD_HOTSPOTS = [
  { x: 20, y: 75, r: 12, intensity: 0.8 },  // Kuching main
  { x: 15, y: 80, r: 8, intensity: 0.6 },   // Kuching secondary
  { x: 25, y: 70, r: 6, intensity: 0.5 },   // Kuching tertiary
  { x: 75, y: 25, r: 10, intensity: 0.7 },  // Miri main
  { x: 80, y: 20, r: 7, intensity: 0.5 },   // Miri secondary
  { x: 45, y: 55, r: 8, intensity: 0.6 },   // Sibu
  { x: 60, y: 40, r: 6, intensity: 0.5 },   // Bintulu
];

// Haptic feedback for iPhone
const triggerHaptic = () => {
  if ('vibrate' in navigator) {
    navigator.vibrate(50); // 50ms vibration
  }
  // iOS doesn't support vibrate API, but the visual feedback helps
};

// Landing page URL for sharing
const LANDING_PAGE_URL = 'https://sarawak-medchain.vercel.app';

// Share to WhatsApp function
const shareToWhatsApp = () => {
  triggerHaptic();

  const message = encodeURIComponent(
    `Hello Councilor,

Here is the MedChain Sarawak Readiness Report.

📊 *Impact Summary*
• Fraud Prevention: RM 2.07 Billion
• Network Status: 24/24 Nodes Active
• Data Integrity: 100% Verified
• Encryption: AES-256-GCM

🏥 *Coverage*
• Kuching Division: 8 hospitals
• Sibu Division: 5 hospitals
• Bintulu Division: 5 hospitals
• Miri Division: 6 hospitals

View full report here:
${LANDING_PAGE_URL}

—
Generated by Sarawak MedChain`
  );

  // WhatsApp deep link - works on both iOS and Android
  const whatsappUrl = `https://wa.me/?text=${message}`;
  window.open(whatsappUrl, '_blank');
};

export default function SarawakReadinessMap() {
  const [selectedDivision, setSelectedDivision] = useState(null);
  const [isZoomed, setIsZoomed] = useState(false);
  const [flyInComplete, setFlyInComplete] = useState(false);
  const [scanLineY, setScanLineY] = useState(0);
  const [isProtected, setIsProtected] = useState(true); // Impact toggle state

  // Fly-in animation: Start zoomed out, then fly into Miri
  useEffect(() => {
    const flyInTimer = setTimeout(() => {
      setSelectedDivision('miri');
      setIsZoomed(true);
      setFlyInComplete(true);
    }, 800);

    return () => clearTimeout(flyInTimer);
  }, []);

  // Scanning line animation for security overlay (only when protected)
  useEffect(() => {
    if (!isProtected) return;

    const scanInterval = setInterval(() => {
      setScanLineY(prev => (prev + 1) % 100);
    }, 50);
    return () => clearInterval(scanInterval);
  }, [isProtected]);

  const activeData = selectedDivision ? DIVISIONS[selectedDivision] : null;

  const handleDivisionClick = (divisionKey) => {
    if (selectedDivision === divisionKey) {
      setSelectedDivision(null);
      setIsZoomed(false);
    } else {
      setSelectedDivision(divisionKey);
      setIsZoomed(true);
    }
  };

  const handleToggle = () => {
    triggerHaptic();
    setIsProtected(!isProtected);
  };

  // Calculate viewBox for zoom effect
  const getViewBox = () => {
    if (!isZoomed || !selectedDivision) {
      return '0 0 100 100';
    }
    const div = DIVISIONS[selectedDivision];
    const x = Math.max(0, div.position.x - 20);
    const y = Math.max(0, div.position.y - 15);
    return `${x} ${y} 45 40`;
  };

  return (
    <div className={`rounded-3xl p-5 relative overflow-hidden transition-all duration-500 ${
      isProtected
        ? 'bg-gradient-to-br from-[#0a0f1a] via-[#0d1525] to-[#0a0f1a] border border-blue-500/20'
        : 'bg-gradient-to-br from-[#1a0a0a] via-[#1f0d0d] to-[#1a0a0a] border border-red-500/30'
    }`}>
      {/* Security scanning grid overlay - only when protected */}
      {isProtected && (
        <div className="absolute inset-0 pointer-events-none overflow-hidden">
          <div className="absolute inset-0 opacity-[0.04]" style={{
            backgroundImage: `
              linear-gradient(rgba(59, 130, 246, 0.8) 1px, transparent 1px),
              linear-gradient(90deg, rgba(59, 130, 246, 0.8) 1px, transparent 1px)
            `,
            backgroundSize: '20px 20px',
          }} />
          <div
            className="absolute left-0 right-0 h-px bg-gradient-to-r from-transparent via-cyan-400 to-transparent opacity-30"
            style={{ top: `${scanLineY}%`, transition: 'top 0.05s linear' }}
          />
          <div
            className="absolute left-0 right-0 h-8 bg-gradient-to-b from-cyan-400/5 to-transparent"
            style={{ top: `${scanLineY}%`, transition: 'top 0.05s linear' }}
          />
        </div>
      )}

      {/* Fraud danger overlay - only when NOT protected */}
      {!isProtected && (
        <div className="absolute inset-0 pointer-events-none overflow-hidden">
          <div className="absolute inset-0 opacity-[0.06]" style={{
            backgroundImage: `
              repeating-linear-gradient(
                45deg,
                rgba(239, 68, 68, 0.3) 0px,
                rgba(239, 68, 68, 0.3) 2px,
                transparent 2px,
                transparent 8px
              )
            `,
          }} />
        </div>
      )}

      {/* Top accent bar */}
      <div className={`absolute top-0 left-0 w-full h-1 transition-all duration-500 ${
        isProtected
          ? 'bg-gradient-to-r from-blue-500 via-amber-500 to-blue-500 opacity-60'
          : 'bg-gradient-to-r from-red-600 via-red-500 to-red-600 opacity-80'
      }`}></div>

      <div className="relative">
        {/* Header with Impact Toggle */}
        <div className="flex flex-col gap-4 mb-4">
          {/* Title - Centered */}
          <div className="flex flex-col items-center text-center">
            <div className={`w-12 h-12 rounded-xl flex items-center justify-center shadow-lg transition-all duration-500 mb-3 ${
              isProtected
                ? 'bg-gradient-to-br from-blue-500 to-blue-600 shadow-blue-500/20'
                : 'bg-gradient-to-br from-red-500 to-red-600 shadow-red-500/20'
            }`}>
              <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                {isProtected ? (
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                ) : (
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                )}
              </svg>
            </div>
            <h2 className="text-xl font-bold text-white mb-1">Sarawak Health Infrastructure</h2>
            <p className={`text-sm transition-colors duration-500 ${isProtected ? 'text-blue-400' : 'text-red-400'}`}>
              {isProtected ? 'AES-256-GCM Protected Network' : 'Unprotected - Fraud Vulnerable'}
            </p>
          </div>

          {/* Impact Toggle Switch - Centered */}
          <div className="flex items-center justify-center">
            <div className={`flex items-center gap-2 p-1 rounded-full transition-all duration-300 ${
              isProtected ? 'bg-emerald-500/10 border border-emerald-500/30' : 'bg-red-500/10 border border-red-500/30'
            }`}>
              <button
                onClick={handleToggle}
                className={`flex items-center gap-2 px-4 py-2 rounded-full text-xs font-bold transition-all duration-300 ${
                  !isProtected
                    ? 'bg-red-500 text-white shadow-lg shadow-red-500/30'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
                Fraud Impact
              </button>
              <button
                onClick={handleToggle}
                className={`flex items-center gap-2 px-4 py-2 rounded-full text-xs font-bold transition-all duration-300 ${
                  isProtected
                    ? 'bg-emerald-500 text-white shadow-lg shadow-emerald-500/30'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                </svg>
                MedChain Protected
              </button>
            </div>
          </div>

          {/* Zoom out button - Centered */}
          {isZoomed && (
            <div className="flex justify-center">
              <button
                onClick={() => { setSelectedDivision(null); setIsZoomed(false); }}
                className="flex items-center gap-1.5 px-4 py-2 bg-white/5 border border-white/10 rounded-lg text-xs text-slate-400 hover:bg-white/10 transition-all"
              >
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0zM13 10H7" />
                </svg>
                Zoom Out
              </button>
            </div>
          )}
        </div>

        {/* Map Container */}
        <div className={`relative rounded-2xl overflow-hidden transition-all duration-500 ${
          isProtected ? 'bg-[#070b14] border border-blue-500/10' : 'bg-[#0f0505] border border-red-500/20'
        }`} style={{ minHeight: '340px' }}>
          {/* SVG Map */}
          <svg
            viewBox={getViewBox()}
            className="w-full h-auto transition-all duration-1000 ease-out"
            style={{ minHeight: '320px' }}
          >
            <defs>
              <radialGradient id="mapGlow" cx="50%" cy="50%" r="50%">
                <stop offset="0%" stopColor={isProtected ? "#1e3a5f" : "#5f1e1e"} stopOpacity="0.4" />
                <stop offset="100%" stopColor="#070b14" stopOpacity="0" />
              </radialGradient>
              <filter id="glow">
                <feGaussianBlur stdDeviation="0.5" result="coloredBlur"/>
                <feMerge>
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
              {/* Red heatmap gradient for fraud */}
              <radialGradient id="fraudHeat">
                <stop offset="0%" stopColor="#ef4444" stopOpacity="0.6" />
                <stop offset="50%" stopColor="#ef4444" stopOpacity="0.3" />
                <stop offset="100%" stopColor="#ef4444" stopOpacity="0" />
              </radialGradient>
            </defs>

            {/* Ocean/Background */}
            <rect x="0" y="0" width="100" height="100" fill={isProtected ? "#070b14" : "#0a0505"} />
            <circle cx="50" cy="50" r="45" fill="url(#mapGlow)" />

            {/* Sarawak landmass - Teal glow effect */}
            <path
              d="M5 88 Q8 78 12 72 L18 68 Q28 62 35 58 L45 52 Q55 44 65 38 L75 28 Q85 20 94 16 L97 22 Q94 32 88 42 L82 52 Q76 60 70 65 L60 70 Q50 74 40 78 L28 82 Q18 86 10 88 L5 88 Z"
              fill={isProtected ? "rgba(20, 184, 166, 0.1)" : "#1a1010"}
              stroke={isProtected ? "#14b8a6" : "#5f2020"}
              strokeWidth={isProtected ? "1.5" : "0.3"}
              style={{
                filter: isProtected ? 'drop-shadow(0 0 10px rgba(20, 184, 166, 0.5))' : 'none',
                transition: 'all 0.5s ease',
              }}
            />

            {/* FRAUD STATE: Red heatmaps */}
            {!isProtected && FRAUD_HOTSPOTS.map((spot, idx) => (
              <circle
                key={idx}
                cx={spot.x}
                cy={spot.y}
                r={spot.r}
                fill="url(#fraudHeat)"
                opacity={spot.intensity}
                className="animate-pulse"
              />
            ))}

            {/* Connection lines - Teal network lines */}
            <g stroke={isProtected ? "#14b8a6" : "#ef4444"} strokeWidth="0.4" opacity={isProtected ? "0.5" : "0.3"} style={{ filter: isProtected ? 'drop-shadow(0 0 3px rgba(20, 184, 166, 0.5))' : 'none' }}>
              <line x1="18" y1="78" x2="45" y2="55" />
              <line x1="45" y1="55" x2="60" y2="40" />
              <line x1="60" y1="40" x2="78" y2="22" />
            </g>

            {/* Division nodes */}
            {Object.entries(DIVISIONS).map(([key, division]) => {
              const isSelected = selectedDivision === key;
              const isMiri = key === 'miri';

              return (
                <g key={key} className="cursor-pointer" onClick={() => handleDivisionClick(key)}>
                  {/* Selection ring */}
                  {isSelected && (
                    <circle
                      cx={division.position.x}
                      cy={division.position.y}
                      r={isZoomed ? 8 : 6}
                      fill="none"
                      stroke={isProtected ? division.color : '#ef4444'}
                      strokeWidth="0.3"
                      opacity="0.6"
                      strokeDasharray="1 1"
                    />
                  )}

                  {/* PROTECTED STATE: Green integrity nodes */}
                  {isProtected ? (
                    <>
                      <circle
                        cx={division.position.x}
                        cy={division.position.y}
                        r={isSelected ? 3 : 2.5}
                        fill="#10b981"
                        filter={isMiri && flyInComplete ? 'url(#glow)' : undefined}
                        className="transition-all duration-300"
                      />
                      <circle
                        cx={division.position.x}
                        cy={division.position.y}
                        r="1"
                        fill="white"
                        opacity="0.5"
                      />
                    </>
                  ) : (
                    /* FRAUD STATE: Red warning nodes */
                    <>
                      <circle
                        cx={division.position.x}
                        cy={division.position.y}
                        r={isSelected ? 3.5 : 3}
                        fill="#ef4444"
                        className="animate-pulse"
                      />
                      <circle
                        cx={division.position.x}
                        cy={division.position.y}
                        r="1.5"
                        fill="#fca5a5"
                        opacity="0.8"
                      />
                    </>
                  )}

                  {/* Division label */}
                  <text
                    x={division.position.x}
                    y={division.position.y - 5}
                    textAnchor="middle"
                    fill={isSelected ? '#ffffff' : '#94a3b8'}
                    fontSize={isZoomed ? '2.5' : '3'}
                    fontWeight="600"
                    className="pointer-events-none select-none"
                  >
                    {division.shortName}
                  </text>

                  {/* Hospital labels - only when zoomed and protected */}
                  {isZoomed && isSelected && isProtected && division.hospitals.map((hospital, idx) => {
                    const angle = (idx / division.hospitals.length) * Math.PI * 2 - Math.PI / 2;
                    const radius = 12 + (idx % 2) * 4;
                    const hx = division.position.x + Math.cos(angle) * radius;
                    const hy = division.position.y + Math.sin(angle) * radius;

                    return (
                      <g key={idx} className="transition-all duration-500" style={{ opacity: flyInComplete ? 1 : 0 }}>
                        <line
                          x1={division.position.x}
                          y1={division.position.y}
                          x2={hx}
                          y2={hy}
                          stroke="#10b981"
                          strokeWidth="0.15"
                          opacity="0.4"
                        />
                        <circle cx={hx} cy={hy} r="1" fill="#10b981" />
                        <rect
                          x={hx - 8}
                          y={hy + 1.5}
                          width="16"
                          height="3"
                          rx="0.5"
                          fill="rgba(255,255,255,0.95)"
                        />
                        <text
                          x={hx}
                          y={hy + 3.5}
                          textAnchor="middle"
                          fill="#0f172a"
                          fontSize="1.5"
                          fontWeight="600"
                          className="pointer-events-none select-none"
                        >
                          {hospital.name}
                        </text>
                      </g>
                    );
                  })}
                </g>
              );
            })}
          </svg>

          {/* Fixed Sidebar - Bottom Left Overlay */}
          <div className="absolute bottom-3 left-3 flex flex-col gap-2">
            {/* Status indicator */}
            <div className={`backdrop-blur-sm rounded-lg px-3 py-2 min-w-[140px] transition-all duration-500 ${
              isProtected
                ? 'bg-[#070b14]/90 border border-emerald-500/30'
                : 'bg-[#0a0505]/90 border border-red-500/30'
            }`}>
              <div className="flex items-center justify-between">
                <span className="text-slate-500 text-[10px] uppercase tracking-wider">
                  {isProtected ? 'Regional Integrity' : 'Fraud Exposure'}
                </span>
                <div className={`w-1.5 h-1.5 rounded-full ${isProtected ? 'bg-emerald-500' : 'bg-red-500 animate-pulse'}`}></div>
              </div>
              <p className={`text-xl font-black ${isProtected ? 'text-emerald-400' : 'text-red-400'}`}>
                {isProtected ? '100%' : 'HIGH'}
              </p>
            </div>

            {/* Financial impact */}
            <div className={`backdrop-blur-sm rounded-lg px-3 py-2 transition-all duration-500 ${
              isProtected
                ? 'bg-[#070b14]/90 border border-amber-500/30'
                : 'bg-[#0a0505]/90 border border-red-500/30'
            }`}>
              <span className="text-slate-500 text-[10px] uppercase tracking-wider">
                {isProtected ? 'Fraud Prevention' : 'Annual Loss'}
              </span>
              <p className={`text-lg font-black ${isProtected ? 'text-amber-400' : 'text-red-400'}`}>
                {isProtected ? 'RM 2.07B' : 'RM 2.3B'}
              </p>
            </div>

            {/* Nodes status */}
            <div className={`backdrop-blur-sm rounded-lg px-3 py-2 transition-all duration-500 ${
              isProtected
                ? 'bg-[#070b14]/90 border border-blue-500/30'
                : 'bg-[#0a0505]/90 border border-red-500/30'
            }`}>
              <span className="text-slate-500 text-[10px] uppercase tracking-wider">
                {isProtected ? 'Active Nodes' : 'Vulnerable Nodes'}
              </span>
              <p className={`text-xl font-black ${isProtected ? 'text-blue-400' : 'text-red-400'}`}>
                24
              </p>
            </div>
          </div>

          {/* Security badge - Bottom Right */}
          <div className={`absolute bottom-3 right-3 flex items-center gap-1.5 px-2.5 py-1.5 backdrop-blur-sm rounded-lg transition-all duration-500 ${
            isProtected
              ? 'bg-[#070b14]/90 border border-cyan-500/30'
              : 'bg-[#0a0505]/90 border border-red-500/30'
          }`}>
            <svg className={`w-3 h-3 ${isProtected ? 'text-cyan-400' : 'text-red-400'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
            <span className={`text-[10px] font-bold ${isProtected ? 'text-cyan-400' : 'text-red-400'}`}>
              {isProtected ? 'AES-256-GCM' : 'UNENCRYPTED'}
            </span>
          </div>

          {/* Division quick-select - Top */}
          <div className="absolute top-3 left-1/2 -translate-x-1/2 flex gap-1.5">
            {Object.entries(DIVISIONS).map(([key, division]) => (
              <button
                key={key}
                onClick={() => handleDivisionClick(key)}
                className={`flex items-center gap-1 px-2 py-1 rounded text-[10px] font-semibold transition-all ${
                  selectedDivision === key
                    ? 'bg-white/15 border border-white/30 text-white'
                    : 'bg-black/40 border border-white/10 text-slate-400 hover:bg-white/10'
                }`}
              >
                <div className={`w-1.5 h-1.5 rounded-full transition-colors duration-500`}
                     style={{ backgroundColor: isProtected ? '#10b981' : '#ef4444' }}></div>
                {division.shortName}
              </button>
            ))}
          </div>
        </div>

        {/* Hospital detail panel */}
        {isZoomed && activeData && isProtected && (
          <div className="mt-3 bg-[#070b14] rounded-xl border border-white/10 overflow-hidden">
            <div className="p-2.5 border-b border-white/10 flex items-center justify-between bg-white/[0.02]">
              <div className="flex items-center gap-2">
                <div className="w-2.5 h-2.5 rounded-full bg-emerald-500"></div>
                <span className="text-white font-semibold text-sm">{activeData.name}</span>
                <span className="text-slate-500 text-xs">• {activeData.hospitals.length} hospitals</span>
              </div>
              <span className="text-emerald-400 text-xs font-semibold">100% Integrity</span>
            </div>

            <div className="p-2.5 grid grid-cols-2 sm:grid-cols-3 gap-2">
              {activeData.hospitals.map((hospital, index) => (
                <div
                  key={index}
                  className="flex items-center gap-2 p-2 bg-white/[0.03] border border-white/5 rounded-lg hover:bg-white/[0.06] active:scale-[0.98] transition-all"
                >
                  <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 flex-shrink-0"></div>
                  <div className="min-w-0">
                    <p className="text-white text-xs font-medium truncate">{hospital.name}</p>
                    <p className="text-slate-500 text-[10px]">{hospital.beds} beds</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Fraud warning panel - when NOT protected */}
        {!isProtected && (
          <div className="mt-3 bg-red-950/50 rounded-xl border border-red-500/30 p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-red-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <svg className="w-5 h-5 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
              </div>
              <div>
                <p className="text-red-400 font-bold text-sm">Malaysia loses RM 2.3 Billion annually</p>
                <p className="text-red-300/70 text-xs">Fake MCs, unverified records, zero audit trail</p>
              </div>
            </div>
            <button
              onClick={handleToggle}
              className="mt-3 w-full py-2 bg-emerald-500 text-white font-bold text-sm rounded-lg hover:bg-emerald-600 transition-all active:scale-[0.98]"
            >
              Activate MedChain Protection →
            </button>
          </div>
        )}

        {/* Share with Councilor - Only when protected */}
        {isProtected && (
          <button
            onClick={shareToWhatsApp}
            className="mt-4 w-full flex items-center justify-center gap-3 py-3.5 px-4 bg-gradient-to-r from-[#25D366] to-[#128C7E] text-white font-semibold text-sm rounded-xl shadow-lg shadow-emerald-500/20 hover:shadow-emerald-500/30 active:scale-[0.98] transition-all"
          >
            {/* iOS Share Sheet Icon */}
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 8.25H7.5a2.25 2.25 0 00-2.25 2.25v9a2.25 2.25 0 002.25 2.25h9a2.25 2.25 0 002.25-2.25v-9a2.25 2.25 0 00-2.25-2.25H15M12 1.5v12m0-12l3 3m-3-3l-3 3" />
            </svg>
            Share Impact Report via WhatsApp
            {/* WhatsApp Icon */}
            <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
              <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
            </svg>
          </button>
        )}
      </div>
    </div>
  );
}
