/**
 * Drives the API continuously while watching for the things that only appear over time:
 * a heap that climbs and never falls, connections that are opened and never returned,
 * an exception nobody caught.
 *
 * A short run cannot prove the absence of a slow leak. What it can do is establish a
 * trend — if the heap is monotonically rising across every sample under a steady, bounded
 * workload, that is a leak; if it saws up and down around a level, that is a garbage
 * collector doing its job.
 *
 *   tsx scripts/soak.ts [minutes] [baseUrl]
 */
import { PrismaClient } from '@prisma/client'

const MINUTES = Number(process.argv[2] ?? 5)
const BASE = process.argv[3] ?? 'http://localhost:4000'
const COMPANY = 'big'
const SITE = 'kch'

const db = new PrismaClient()

const login = async (email: string) => {
  const r = await fetch(`${BASE}/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password: 'SafeOpsPlatform2026' }),
  })
  if (!r.ok) throw new Error(`login ${email}: ${r.status}`)
  return ((await r.json()) as { accessToken: string }).accessToken
}

const hse = await login('hse@demo.safeops.app')
const officer = await login('officer@demo.safeops.app')
const auth = (t: string) => ({ Authorization: `Bearer ${t}`, 'Content-Type': 'application/json' })

let requests = 0
let failures = 0
const statuses = new Map<number, number>()

const call = async (method: string, path: string, token: string, body?: unknown) => {
  requests++
  try {
    const r = await fetch(`${BASE}${path}`, {
      method,
      headers: auth(token),
      body: body === undefined ? undefined : JSON.stringify(body),
    })
    statuses.set(r.status, (statuses.get(r.status) ?? 0) + 1)
    if (r.status >= 500) failures++
    return r
  } catch {
    failures++
    statuses.set(0, (statuses.get(0) ?? 0) + 1)
    return null
  }
}

/** Reads a real workspace the way the dashboard does. */
const readCycle = async () => {
  await Promise.all([
    call('GET', `/incidents?companyId=${COMPANY}&pageSize=100`, hse),
    call('GET', `/incidents/stats?companyId=${COMPANY}`, hse),
    call('GET', `/incidents/actions/list?companyId=${COMPANY}&pageSize=100`, hse),
    call('GET', `/permits?companyId=${COMPANY}&pageSize=100`, hse),
    call('GET', `/assets?companyId=${COMPANY}`, hse),
    call('GET', `/audits?companyId=${COMPANY}`, hse),
    call('GET', `/training/matrix?companyId=${COMPANY}`, hse),
    call('GET', `/activity?companyId=${COMPANY}`, hse),
    call('GET', `/notifications?companyId=${COMPANY}`, hse),
  ])
}

/** Writes, so the soak exercises transactions and the counters, not just reads. */
let created = { incidents: 0, permits: 0 }
const writeCycle = async (n: number) => {
  const inc = await call('POST', '/incidents', officer, {
    companyId: COMPANY, siteId: SITE, title: `Soak incident ${n}`,
    type: 'near_miss', severity: 'Minor', location: 'Soak bay',
    occurredAt: new Date().toISOString(), description: 'Generated by the stability soak.',
  })
  if (inc?.ok) created.incidents++

  const from = new Date(Date.now() + 3600_000)
  const permit = await call('POST', '/permits', officer, {
    companyId: COMPANY, siteId: SITE, type: 'working_at_height',
    title: `Soak permit ${n}`, location: 'Soak tower', applicant: 'Ganesh Pillai',
    validFrom: from.toISOString(), validTo: new Date(from.getTime() + 4 * 3600_000).toISOString(),
  })
  if (permit?.ok) created.permits++
}

const samples: { t: number; rssMB: number; heapMB: number; conns: number }[] = []

const sample = async () => {
  const rows = await db.$queryRaw<{ count: bigint }[]>`
    SELECT count(*)::bigint AS count FROM pg_stat_activity WHERE datname = current_database()
  `
  const mem = process.memoryUsage()
  samples.push({
    t: Date.now(),
    rssMB: Math.round(mem.rss / 1048576),
    heapMB: Math.round(mem.heapUsed / 1048576),
    conns: Number(rows[0]?.count ?? 0),
  })
}

console.log(`\nSoaking ${BASE} for ${MINUTES} minute(s)…\n`)
console.log('elapsed   requests  fail  5xx-free  db-conns  probe-rss  probe-heap')
console.log('─'.repeat(72))

const started = Date.now()
const until = started + MINUTES * 60_000
let cycle = 0

while (Date.now() < until) {
  cycle++
  await readCycle()
  if (cycle % 5 === 0) await writeCycle(cycle)

  if (cycle % 10 === 0) {
    await sample()
    const s = samples[samples.length - 1]
    const elapsed = Math.round((Date.now() - started) / 1000)
    console.log(
      `${String(elapsed).padStart(5)}s ${String(requests).padStart(10)} ${String(failures).padStart(5)}` +
      `${(failures === 0 ? '       yes' : '        NO').padStart(10)} ${String(s.conns).padStart(9)}` +
      ` ${String(s.rssMB).padStart(10)}MB ${String(s.heapMB).padStart(9)}MB`,
    )
  }
  // Paced to stay inside the 600/min ceiling. Without this the soak measures the rate
  // limiter rather than the application — a useful result once, and then noise.
  await new Promise((r) => setTimeout(r, 1000))
}

await sample()

console.log('─'.repeat(72))
console.log(`requests        : ${requests}`)
console.log(`5xx / transport : ${failures}`)
console.log(`status spread   : ${[...statuses.entries()].sort().map(([s, n]) => `${s}×${n}`).join('  ')}`)
console.log(`created         : ${created.incidents} incidents, ${created.permits} permits`)

const conns = samples.map((s) => s.conns)
const heaps = samples.map((s) => s.heapMB)
console.log(`db connections  : min ${Math.min(...conns)}  max ${Math.max(...conns)}  last ${conns[conns.length - 1]}`)
console.log(`probe heap      : min ${Math.min(...heaps)}MB  max ${Math.max(...heaps)}MB  last ${heaps[heaps.length - 1]}MB`)

// A leak shows as every sample being higher than the one before it.
const monotonic = heaps.every((h, i) => i === 0 || h >= heaps[i - 1])
console.log(`heap trend      : ${monotonic && heaps.length > 3 ? 'MONOTONICALLY RISING — investigate' : 'sawtooth (normal)'}`)

await db.$disconnect()
